language: python

cache: pip

matrix:
  include:
  - python: '3.5'
  - python: '3.6'
  - python: '3.7'
    dist: xenial
    sudo: required
  - python: '3.8-dev'
    dist: xenial
    sudo: required

  allow_failures:
  - python: '3.8-dev'

install:
- make install-test
- pip freeze

script:
- make lint
- make test
- make docs
- ./tests/check_tag.py

after_success:
- ls -lha
- bash <(curl -s https://codecov.io/bash)

env:
- secure: "WnCglysfnXwLAlzgJAkkOvXmQdYMqdPoSu820IFzg4ul1bh75i1b1C8jmxECESXew5IGAbmgjSBYErKeYktT9EMpXkSNRMF7k64JhbN9D8Fr5IhB62UfuJc/u0vIf/6mJc8oByvVCsJ+9i8PzJ98BBQMduFtsh3RjU+JoClcE+H+u1ieH7L23/lEq+no9iUbJyPg6LOHmfbU5YIP5hTHYqNIHnx8/0jwI9UhFXfFzPIl0smyECKNR3BOj/4Mntd5gFq3XNXf5MZir0gZhmg+J79POC0JqzUXGnZy27Dw6xPnOVOuIwjib6qcquM1cCAq1wRExab5p4CskmWqGkAwYMbrh15Za6Xzvt7iuP91aAptffHh1ztT2Ff48fXY354ZF2u5hfEsSV3O4kPz8LfOOiox0Vw+ohUvxfkg9NphpbOfwgPpL+TdMjhIjnnVBLOSE4UMlIxbFGmM2HooW18mXoPXCu66nm+Rz7jsXuV8OsamRWqvqd58pNbzyuxhUZwM3CzggT/1qAIhN8tEzBjL7Klei5fHgU+2Nm5T0m4s+UJNRCwJn/k6cOF2vxYMbjTxFsquoOd98aXGpCWUtOwzyjNz+6SA4ltlrUJnMpgXLAp+Z0qSfZJP9FUzjryWbfsQdmUhcYfAe5BFFegcQPmcJnQ127r5CqP+l3vO+H7Eetw="

deploy:
- provider: pypi
  user: samuelcolvin
  password:
    secure: "IM+wrXKm12InmgGmLrvms7r2mXsG3cAdsIr2A24HnXCPaxDsg0ShZ/g9Xy1T9S2EmJZUcK53Qx09yoIvXvvS5mx0JKDbb95N+dsw3IFQYsCzFDPqlLQGgiFFy8hC5sEVBp3FXh1VPkG8XOvq514cUp+wmyslX1TnEG9lf2TaOo3Zk9FZQzg+UVIj/8vpheOZIGEhADkOImlyG0yIRA7Ehthslhr3clYK2d+4UGZ9KTSdG0kkFjAj5zPeQpWTCJmkWbygU4s85y2sZAmUDwUKq9uv3ACUrFdNXK4yMrYCKv+1+hB/P9F9vhX1zOb3vhbOub1xwBYDaiFOVsAFWCNkQhWa7SZ12bb4enb3ZbY1bZBv8EfPyY9EejAjEBkJ4cGFusQf2I0s8VtmJ3nvYysVco0QNg83EDvNybT7RTObI8mqDgfzdLgHSk3p7nhVjZX6LCeEx2tlU/Z3mOn8h2q/Kzl9JixEuuIyE42meW3DnM4Ffryc3ocgLBBasl5pULcT5ooixpMhmr8Y6SIV677MWi+Bxifepv/LiqyaeKdnZFzabArqn8/MOaR2Q6ucMLNZWXqYGNQXjSh1f378ibl6Xoic3sVDVVPaOWNcPxmmFdCQ0SvDhYGR/4KiqNvngd34c5Pc1Q/F20fpkbVdFkCu66Z+z939epC+4XWZ0VIrW+s="
  distributions: sdist bdist_wheel
  skip_upload_docs: true
  on:
    tags: true
    python: 3.6
- provider: script
  script: make publish
  on:
    tags: true
    python: 3.6
